- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install numpy matplotlib seaborn requests
- name: Configure matplotlib
  run: |
    echo "backend: Agg" > matplotlibrc
    export MPLBACKEND=Agg
- name: Log setup time
  run: echo "Setup completed at $(date)"
- name: Run training script
  run: |
    sleep 1
    python train_model.py &
- name: Wait and trigger next run
  run: |
    sleep 270  # Wait 4:30 to ensure trigger
    echo "Triggering next workflow run"
  continue-on-error: true
- name: Trigger self
  uses: actions/github-script@v6
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      await github.rest.actions.createWorkflowDispatch({
        owner: context.repo.owner,
        repo: context.repo.repo,
        workflow_id: 'main.yml',
        ref: 'main'
      });
  continue-on-error: true
