name: Run Model Training

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model-1:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py

  train-model-2:
    needs: train-model-1
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py

  train-model-3:
    needs: train-model-2
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py

  train-model-4:
    needs: train-model-3
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py

  train-model-5:
    needs: train-model-4
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py

  train-model-6:
    needs: train-model-5
    runs-on: ubuntu-latest
    timeout-minutes: 200

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib seaborn requests

    - name: Configure matplotlib
      run: |
        echo "backend: Agg" > matplotlibrc
        export MPLBACKEND=Agg

    - name: Run training script
      run: python train_model.py
